# Example camera parameters (for Bumblebee2)

# Parameters (no lens required/used)
guid: 00b09d0100ad589b          # (defaults to first camera on bus)
iso_speed: 400  # IEEE1394a
# Stereo interlaced
stereo_method: Interlaced
video_mode: format7_mode3   # 1024x768 @ 20fps bayer pattern
# Note that frame_rate is overwritten by frame_rate_feature; some useful values:
# 1.875fps (2658), 7.5fps (1544), 15fps (800), 20fps (480)
frame_rate: 1.875 # max fps (Hz)
auto_frame_rate_feature: 3 # Manual (3)
frame_rate_feature: 2658
format7_color_coding: raw16  # for bayer and Stereo interlaced
# With raw16, we don't need to configure bayer pattern and method, actually we
# cannot change them
bayer_pattern: grbg
bayer_method: HQ
auto_brightness: 3 # Manual (3)
brightness: 0
auto_exposure: 3 # Manual (3)
exposure: 350
# Is better to increase gain than shutter speed, becuase gain produce salt&pepper
# noise, while shutter speed produce motion blur, which is harder to deal with.
auto_gain: 3 # Manual (3)
gain: 426 # approx. 15dB
# We cannot set gamma manually in ROS (electric), so we don't touch it
# It must be set to Manual (3) with value 4095 (max, approx. gamma 4)
#auto_gamma: 0 # Off (0)
#gamma: 1024    # gamma 1
auto_saturation: 3 # Manual (3)
saturation: 1000
auto_sharpness: 3 # Manual (3)
sharpness: 1000
# See comment above wrt to gain and shutter speed setting.
auto_shutter: 3 # Manual (3)
shutter: 264 # approx. 12.5ms
auto_white_balance: 3 # Manual (3)
white_balance_BU: 613
white_balance_RV: 677
frame_id: bumblebee2
# Calibration files are taken from the not slow version,
# because they're the same.
camera_info_url_left: package://cameras_cirs/calibration/bumblebee2/format7_mode3/${NAME}.yaml
camera_info_url_right: package://cameras_cirs/calibration/bumblebee2/format7_mode3/${NAME}.yaml
strobe: false

