# Determine the publish rate of the diagnostics aggregator
pub_rate: 1.0

# The following parameters are used to categorize the data from the diagnostics
# in order to display the desired hierarchy in the robot_monitor tool
base_path: ''
analyzers:
  navigation:
    type: GenericAnalyzer
    path: navigation
    name: [
        '/navigator',
        '/fastrax_it_500_gps',
        '/teledyne_explorer_dvl'
    ]

  control:
    type: GenericAnalyzer
    path: control
    name: [
        '/teleoperation',
        '/captain',
        '/hug_actuators',
        '/controller',
        'joystick: Joystick Driver Status'
    ]

  safety:
    type: GenericAnalyzer
    path: safety
    name: [
        '/safe_depth_altitude',
        '/virtual_cage',
        '/up_time',
        '/safety_supervisor',
        '/battery',
        '/check_sensors',
        '/hug_mon_control_board',
        '/evologics_modem',
        '/computer_logger'
    ]

