# Enbale thrusters
controller/enable_thrusters: False

# POSE PID CONTROLLER
# The following parameters adjust the proportional–integral–derivative
# controllers for each degree of freedom (DOF). i_limit represents the maximum
# value the integral part can take (anti-windup), and fff allows a feed-forward
# force to be specified (sometimes useful for the heave controller)
controller/p_surge_kp: 0.0
controller/p_surge_ti: 0.0
controller/p_surge_td: 0.0
controller/p_surge_i_limit: 0.0
controller/p_surge_fff: 0.0

controller/p_sway_kp: 0.0
controller/p_sway_ti: 0.0
controller/p_sway_td: 0.0
controller/p_sway_i_limit: 0.0
controller/p_sway_fff: 0.0

controller/p_heave_kp: 1.2
controller/p_heave_ti: 0.0
controller/p_heave_td: 0.0
controller/p_heave_i_limit: 0.0
controller/p_heave_fff: 0.0

controller/p_roll_kp: 0.0
controller/p_roll_ti: 0.0
controller/p_roll_td: 0.0
controller/p_roll_i_limit: 0.0
controller/p_roll_fff: 0.0

controller/p_pitch_kp: 0.0
controller/p_pitch_ti: 0.0
controller/p_pitch_td: 0.0
controller/p_pitch_i_limit: 0.0
controller/p_pitch_fff: 0.0

controller/p_yaw_kp: 0.5
controller/p_yaw_ti: 0.0
controller/p_yaw_td: 2.0
controller/p_yaw_i_limit: 0.0
controller/p_yaw_fff: 0.0

# Maximum velocity for each DOF
/controller/max_velocity_x: 2.0
/controller/max_velocity_y: 0.0
/controller/max_velocity_z: 0.30
/controller/max_velocity_roll: 0.0
/controller/max_velocity_pitch: 0.0
/controller/max_velocity_yaw: 0.30

# Twist (velocity) PID controller
controller/t_surge_kp: 0.25
controller/t_surge_ti: 20.0
controller/t_surge_td: 0.0
controller/t_surge_i_limit: 0.25
controller/t_surge_fff: 0.0

controller/t_sway_kp: 0.0
controller/t_sway_ti: 0.0
controller/t_sway_td: 0.0
controller/t_sway_i_limit: 1.0
controller/t_sway_fff: 0.0

controller/t_heave_kp: 5.0
controller/t_heave_ti: 0.0
controller/t_heave_td: 4.0
controller/t_heave_i_limit: 0.0
controller/t_heave_fff: 0.05 #0.26

controller/t_roll_kp: 0.0
controller/t_roll_ti: 0.0
controller/t_roll_td: 0.0
controller/t_roll_i_limit: 1.0
controller/t_roll_fff: 0.0

controller/t_pitch_kp: 0.0
controller/t_pitch_ti: 0.0
controller/t_pitch_td: 0.0
controller/t_pitch_i_limit: 1.0
controller/t_pitch_fff: 0.0

controller/t_yaw_kp: 2.5
controller/t_yaw_ti: 8.0
controller/t_yaw_td: 0.0
controller/t_yaw_i_limit: 0.15
controller/t_yaw_fff: 0.0

# Parameters for a feed-forward polynomial model for each DOF (A+B*x+C*x^2)
controller/poly_surge_A: 0.0
controller/poly_surge_B: 9.9239
controller/poly_surge_C: 10.1728

controller/poly_sway_A: 0.0
controller/poly_sway_B: 0.0
controller/poly_sway_C: 0.0

controller/poly_heave_A: 0.0
controller/poly_heave_B: 0.0
controller/poly_heave_C: 259.8366

controller/poly_roll_A: 0.0
controller/poly_roll_B: 0.0
controller/poly_roll_C: 0.0

controller/poly_pitch_A: 0.0
controller/poly_pitch_B: 0.0
controller/poly_pitch_C: 0.0

controller/poly_yaw_A: 0.0
controller/poly_yaw_B: 0.0
controller/poly_yaw_C: 53.2837

# The following values (must be between 0 and 1) adjust the percentage of
# polynomial model that is used. A value of 1 means than the model is fully
# taken into account in conjunction with the PID. A value of 0 means that the
# model is not used
controller/poly_surge_percentatge: 1.0
controller/poly_sway_percentatge: 0.0
controller/poly_heave_percentatge: 1.0
controller/poly_roll_percentatge: 0.0
controller/poly_pitch_percentatge: 0.0
controller/poly_yaw_percentatge: 1.0

# Maximum wrench (force) for each DOF
/controller/max_wrench_X: 154.0
/controller/max_wrench_Y: 0.0
/controller/max_wrench_Z: 30.0
/controller/max_wrench_Roll: 3.66
/controller/max_wrench_Pitch: 17.15
/controller/max_wrench_Yaw: 14.43

# Thruster force parameters. If the propeller is changed these values must be
# updated
/controller/max_force_thruster_forward: 77.0
/controller/max_force_thruster_backward: 43.0


# Thruster control matrix. This matrix specifies how each thruster contributes
# to the force or torque generated in each axis of the robot
# /controller/TCM: [0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.16783, 0.16783]
/controller/TCM: [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# FINS CONFIGURATIONS

# DEPTH TO PITCH PID CONTROLLER
# controller/d_p_kp: 0.15
# controller/d_p_ti: 12.0
# controller/d_p_td: 0.0
# controller/d_p_limit: 0.2
# controller/d_p_fff: 0.0

# ROLL PID CONTROLLER
# controller/f_roll_kp: 0.4
# controller/f_roll_ti: 15.0
# controller/f_roll_td: 0.0
# controller/f_roll_i_limit: 0.25
# controller/f_roll_fff: 0.0

# YAW PID CONTROLLER
controller/f_yaw_kp: 0.4
controller/f_yaw_ti: 15.0
controller/f_yaw_td: 0.0
controller/yaw_i_limit: 0.25
controller/yaw_fff: 0.0

# PITCH PID CONTROLLER
controller/f_pitch_kp: 0.8
controller/f_pitch_ti: 15.0
controller/f_pitch_td: 8.0
controller/f_pitch_i_limit: 0.1
controller/f_pitch_fff: 0.0

# FIN ALLOCATOR
/controller/max_fin_force: 26.15
/controller/fin_distance_surge: 0.65
/controller/fin_distance_yaw: 0.14
/controller/max_fin_angle: 40.0
/controller/min_fin_angle: -40.0

/controller/force_to_fins_ratio: 13.0

# /controller/FCM: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.14, 0.14, 0.65, 0.65, 0.0, 0.0]
/controller/FCM: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.65, 0.65, 0.0]
/controller/fin_poly: [0.0, 1.0, 0.0, 0.0, 1.0, 0.0]
