# Transformation wrt vehicle frame: [x, y, z, roll, pitch, yaw] (in meters and degrees!!!)
tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
frame_id: "/hug"

# range: 5, 10, 20, 30, 40, 50
range: 20

# auto_range: 2
auto_range: 2

# gain 0dB to 40dB
gain: 10

# auto_gain 0x01: True, 0x02:False
auto_gain: 2

# pulse length: 10 = 0x0A
pulse_length: 10

# min range: 0
min_range: 0

# data points: 25 = 0x19
data_points: 25

# profile: 1
profile: 1

# switch delay: 1
switch_delay: 1

# echosounders order: 17, 18, 19, 20, 21
echosounders_order: [17, 18, 19, 20, 21, 18, 19]

# serial port
#serial_port: '/dev/ttyUSB0'
serial_port: '/dev/ttyS11'

# digital_output: 2
# device_timeout: 1000
# Max time per file in seconds
# file_max_time: 30
# device_addr: "192.168.0.7"
# device_port: 4040
# If frequency Low (0)/Medium(1), range: 10,20,30,40,50,60,80,100,125,150,200
# If frequency High (2), range: 10,20,30,40,50
# frequency: 0
# range: 10
# 0 to 60 => +/-3dB on 0.1dB increments
# balance_gain: 30


