# Transformation wrt vehicle frame: [x, y, z, roll, pitch, yaw] (in meters and degrees!!!)
imagenex_side_scan_sonar/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
imagenex_side_scan_sonar/frame_id: "hug"

imagenex_side_scan_sonar/automatic_sound_speed: True

imagenex_side_scan_sonar/digital_output: -1
imagenex_side_scan_sonar/device_timeout: 1000

# Max time per file in seconds
imagenex_side_scan_sonar/file_max_time: 60

imagenex_side_scan_sonar/device_addr: "192.168.0.5"
imagenex_side_scan_sonar/device_port: 4040

# If frequency Low (0)/Medium(1), range: 10,20,30,40,50,60,80,100,125,150,200
# If frequency High (2), range: 10,20,30,40,50
imagenex_side_scan_sonar/frequency: 2
imagenex_side_scan_sonar/range: 20

# gain 0dB to 40dB
imagenex_side_scan_sonar/data_gain: 16

# 0 to 60 => +/-3dB on 0.1dB increments
imagenex_side_scan_sonar/balance_gain: 30
