# Transformation wrt vehicle frame: [x, y, z, roll, pitch, yaw] (in meters and degrees!!!)
imagenex_multibeam_sonar/tf: [0.5, 0.0, 0.0, 0.0, -90.0, 180.0] # down_looking sparus standard payload
# imagenex_multibeam_sonar/tf: [0.58, 0.0, 0.08, 0.0, -90.0, 0.0] # (down-looking)
#imagenex_multibeam_sonar/tf: [0.5, 0.0, 0.41, -90.0, 180.0, -90.0] # side-looking (to the right) for l'Amarrador experiments
imagenex_multibeam_sonar/frame_id: "hug"

imagenex_multibeam_sonar/digital_output: -1

# Valid Ranges: 5, 10, 20, 30, 40, 50, 60, 80, 100
# If range <= 0, range is set automatically according to (DVL) altitude
imagenex_multibeam_sonar/range: 5 #

#Valid Gain: 1 - 20
imagenex_multibeam_sonar/gain: 10

#Sector size: 0 = 30deg, 1 = 60deg, 2 = 90deg, 3 = 120deg
imagenex_multibeam_sonar/sector_size: 3

#Beamwidth: 0 = Wide, 1 = Normal, 2 = Narrow, 3 = Narrow Mixed
imagenex_multibeam_sonar/beamwidth: 1

# Number of beams: 480, 240, 120
imagenex_multibeam_sonar/nbeams: 480

# Number of beams to average: 3, 5, 7 or 9
imagenex_multibeam_sonar/averaging: 5

# Enable recording of 837 file
imagenex_multibeam_sonar/record_837: true

# Profile point filter: 0=First return, 1=Maximum Return 2=Bottom Following
imagenex_multibeam_sonar/profile_point_filter: 2

# Sound speed is set on the launch file.
# However, if automatic_sound_speed is "true", it will be updated according to SVS sound velocity sensor.
imagenex_multibeam_sonar/automatic_sound_speed: false

# Enable output of .83P or .83B files
# 0: .83P, 1: .83B
imagenex_multibeam_sonar/output_83: 0

# Connexion
imagenex_multibeam_sonar/device_addr: "192.168.0.2"
imagenex_multibeam_sonar/device_port: "4040"

