# Sonar Type
name: "micron"
sonar_type: "micron"

# Dynamic Parameters
rangeScale: 10
cont: false
#llim: 0
#rlim: 360
llim: 120 # 315
rlim: 240 # 45
igain: 45
soundSpeed: 1500
soundSpeedAutomatic: false
min_range: 0.5
step: 2
nbins: 400

# Sensor static parameters
adlow: 0
adspan: 255
adc8on: True
scanright: True
invert: false
spPath: "/dev/ttyS4"
spBaudRate: 115200
spCharSize: 8
spStopBits: 1
spParity: "NONE"
spFlowControl: "NONE"
spTimeout: 10000
spPeriod: 100
slope1: 110
slope2: 150
channel2: True

# Transformation
# Sparus2 horizontal
tf_x: 0.885 # 0.7
tf_y: 0.0
tf_z: -0.21 # -0.15
tf_roll: 0.0
tf_pitch: 0.0
tf_yaw: 3.14159
frame_id: "hug"
child_id: "micron"
# Sparus2 vertical
#tf_x: 0.918
#tf_y: 0.0
#tf_z: -0.09
#tf_roll: 3.14159
#tf_pitch: 1.57
#tf_yaw: 0
#frame_id: "sparus2"
#child_id: "micron"
