# Initialize EKF filter using GPS information
navigator/initialize_filter_from_gps: true

# Apply GPS updates in the EKF filter
navigator/use_gps_data: true

# if true use current gps position as ned origin, otherwise use predefined ned origin
navigator/initialize_ned_from_gps: false

# Define NED origin if initialize_ned_from_gps is set to false
navigator/ned_latitude: 41.7773700755 #42.954 #38.5200248466315 # 41.768860505
navigator/ned_longitude: 3.03875848166 #10.602 #-28.6320306729769 # 3.03170557637

# Apply updates comming from USBL. Evologics modem and external USBL must be running
navigator/use_usbl_data: false

# Set spot current magnetic declination in degrees (http://www.magnetic-declination.com/)
navigator/declination_in_degrees: 0.5

# If GPS is used to initialize the filter (vehicle on surface) initialize also depth sensor offset?
navigator/initialize_depth_sensor_offset: true

# When the vehicle is on surface, distance between water surface and depth sensor (used by initialize_depth_sensor_offset)
navigator/surface_to_depth_sensor_distance: 0.05

# Depth sensor offset value is not used if initialize depth sensor offset is set to true 
# and there is GPS. Depth sensor offeset is directly added to measured depth.
navigator/depth_sensor_offset: -1.0

# Depth sensor correction. This value is added to the depth in meters
navigator/water_density: 1000  # Pool -> 1000 Sea -> 1030?

# Define world and vehicle TFs
navigator/robot_frame_id: "/hug"
navigator/world_frame_id: "/world"

# Sensors/Model covariances
navigator/dvl_bottom_covariance: [0.002, 0.002, 0.002]
navigator/dvl_water_covariance: [0.02, 0.02, 0.02]
navigator/gps_covariance: [0.5, 0.5]
navigator/usbl_covariance: [0.25, 0.25]
navigator/pressure_covariance: 0.1
navigator/model_covariance: [0.02, 0.02, 0.02]

# If DVL data > "navigatior/dvl_max_v" (m/s) discard it
navigator/dvl_max_v: 1.5

# ATTENTION: ALL THESE TFs SHOULD BE ALREADY BUBLISHED!!!
# Define Extra TFs needed by the navigator
bumblebee2/tf: [0.45, -0.06, -0.12, 80.0, 0.0, 90.0]
g500/stereo_front/tf: [0.45, -0.06, -0.12, 80.0, 0.0, 90.0]
usbl_head/tf: [-0.5, 0.0, 0.1, 0.0, 0.0, 0.0]
fastrax_it_500_gps/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
pressure_sensor/tf: [0.389, 0.0, 0.0, 0.0, 0.0, 0.0]
adis_imu/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
teledyne_explorer_dvl/tf: [0.0, 0.0, 0.0, 180.0, 0.0, 135.0]
evologics/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
