# SPARUS2 SAFETY CONFIG

# Timeout and minimum update times for the safety supervisor
safety/timeout: 3600  # Seconds
safety/min_imu_update: 10.0
safety/min_depth_update: 10.0
safety/min_altitude_update: 60.0
safety/min_gps_update: 30.0
safety/min_dvl_update: 20.0
safety/min_nav_update: 2.0
safety/min_wifi_update: 30.0
safety/min_modem_update: 400

# USBL
safety/usbl_safety_always_on: false

# DVL
safety/min_dvl_good_data: 200

# Battery
safety/min_battery_charge: 0.0
safety/min_battery_voltage: 0.0
safety/min_distance_to_wall: 5.0 #MORPH only

# Max Temperatures: 
safety/max_temperatures_ids: ['batteries', 'pc', 'thrusters']
safety/max_temperatures_values: [55.0, 80.0, 95.0]

# Maximum allowed distance to a waypoint. Just for safety reasons
/captain/max_distance_to_waypoint: 750.0

# Recovery actions
recovery_actions/frame_id: "hug"
# Be careful here! TH 0 1 2 vertical is 0 (-) values are for surface
recovery_actions/emergency_surface_setpoints: [-0.30, 0.0, 0.0]
recovery_actions/controlled_surface_depth: 0.0

# Safe max depth & min altitude
safe_depth_altitude/max_depth: 12.0
safe_depth_altitude/min_altitude: 0.8

# Set zero velocity
safety_set_zero_velocity/set_zero_velocity_depth: 1.0
safety_set_zero_velocity/set_zero_velocity_axis: [[False, True, True, True, True, True], [True, True, False, True, True, True], [True, True, True, True, True, False]]


# Parameters for the set_pose node. Define as many 6DoF tuples as you want
# indicating which DoFs must be set to desired_pose (False) and which not (True)
safety_set_pose/set_pose_axis: [[True, True, True, True, False, True],[True, True, True, False, True, True]]
safety_set_pose/desired_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
safety_set_pose/set_pose_depth: 2.0

# Define virtual cage (the vehicle is not allowed to move outside of this area)
virtual_cage/north_origin: -500.0
virtual_cage/east_origin: -500.0
virtual_cage/north_longitude: 1000.0
virtual_cage/east_longitude: 1000.0
virtual_cage/enabled: true
