# Minimum and maximum positions for each degree of freedom (DOF)
teleoperation/max_pos: [0.0, 0.0, 5.0, 3.14159265359, 1.0, 3.14159265359]
teleoperation/min_pos: [0.0, 0.0, -2.0, -3.14159265359, -1.0, -3.14159265359]

# Minimum and maximum velocities for each degree of fredom (m/s or rad/s)
teleoperation/max_vel: [0.6, 0.0, 0.3, 0.0, 0.0, 0.3]
teleoperation/min_vel: [-0.6, 0.0, -0.3, 0.0, 0.0, -0.3]

# Initial state of the controllers (pose vs. velocity)
teleoperation/pose_controlled_axis: [False, False, False, False, False, False]

# Initial pose for the pose controllers
teleoperation/base_pose: [0, 0, 0, 0, 0, 0]

# Use current pose as base pose when the pose controllers are activated
teleoperation/actualize_base_pose: true
