/teledyne_explorer_dvl/tf: [0.0, 0.0, 0.0, 180.0, 0.0, 135.0]
/run_id: '358b6aa2-0eef-11e7-a703-9bb342f32036'
/fastrax_it_500_gps/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/sea_bottom_depth: 15.0
/bumblebee2/tf: [0.45, -0.06, -0.12, 80.0, 0.0, 90.0]
/robot_name: 'hug'
/dynamics/current_sigma: [0.001, 0.001, 0.001]
/dynamics/hug/ned_origin_longitude: 3.03876
/dynamics/hug/odom_topic_name: '/hug/ros_odom_to_pat'
/dynamics/hug/number_of_thrusters: 3
/dynamics/hug/period: 0.05
/dynamics/hug/force_topic: '/cola2_control/merged_body_force_req'
/dynamics/hug/radius: 0.115
/dynamics/hug/max_thrusters_rpm: 1200
/dynamics/hug/buoyancy: 57.5
/dynamics/hug/use_force_topic: True
/dynamics/hug/tensor: [0.38545, 0.0, 0.0, 0.0, 11.28606, 0.0, 0.0, 0.0, 11.28606]
/dynamics/hug/thrusters_matrix: [[0.0, 1.0, 1.0], [0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, -0.16, 0.16]]
/dynamics/hug/density: 1030.0
/dynamics/hug/thrusters_topic: '/cola2_control/sim_thrusters_data'
/dynamics/hug/quadratic_damping: [-10.1728, -259.8366, -259.8366, -5.0, -53.2837, -53.2837]
/dynamics/hug/damping: [-9.9239, 0.0, 0.0, -1.0, 0.0, 0.0]
/dynamics/hug/gravity_center: [0.0, 0.0, 0.02]
/dynamics/hug/initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/dynamics/hug/number_of_fins: 2
/dynamics/hug/dh: 0.4
/dynamics/hug/max_fins_angle: 0.3941
/dynamics/hug/world_frame_id: 'world'
/dynamics/hug/frame_id: 'hug_dynamics'
/dynamics/hug/initial_velocity: [0, 0, 0, 0, 0, 0]
/dynamics/hug/dv: 0.05
/dynamics/hug/altitude_range_topic_name: '/hug/range'
/dynamics/hug/g: 9.80665
/dynamics/hug/a_fins: 0.0094
/dynamics/hug/ctf: 4.861111e-05
/dynamics/hug/mass: 56
/dynamics/hug/k_cd_fins: 1.8
/dynamics/hug/ctb: 4.861111e-05
/dynamics/hug/dzv: 0.05
/dynamics/hug/uwsim_contact_sensor: ''
/dynamics/hug/ned_origin_latitude: 41.77737
/dynamics/hug/fins_topic: '/cola2_control/sim_fins_data'
/dynamics/hug/k_cl_fins: 1.1
/dynamics/current_max: [1.0, 1.0, 1.0]
/dynamics/current_mean: [-0.3, 0.1, 0.0]
/dynamics/current_enabled: False
/dynamics/current_min: [-1.0, -1.0, -1.0]
/navigator/initialize_filter_from_gps: True
/navigator/dvl_water_covariance: [0.02, 0.02, 0.02]
/navigator/dvl_max_v: 1.5
/navigator/use_usbl_data: False
/navigator/initialize_depth_sensor_offset: True
/navigator/model_covariance: [0.02, 0.02, 0.02]
/navigator/pressure_covariance: 0.1
/navigator/dvl_bottom_covariance: [0.002, 0.002, 0.002]
/navigator/declination_in_degrees: 0.5
/navigator/use_gps_data: True
/navigator/surface_to_depth_sensor_distance: 0.05
/navigator/water_density: 1000
/navigator/ned_longitude: 3.03875848166
/navigator/robot_frame_id: '/hug'
/navigator/world_frame_id: '/world'
/navigator/ned_latitude: 41.7773700755
/navigator/usbl_covariance: [0.25, 0.25]
/navigator/initialize_ned_from_gps: False
/navigator/depth_sensor_offset: -1.0
/navigator/gps_covariance: [0.5, 0.5]
/usbl_head/tf: [-0.5, 0.0, 0.1, 0.0, 0.0, 0.0]
/virtual_cage/enable: True
/virtual_cage/north_longitude: 1000.0
/virtual_cage/east_origin: -500.0
/virtual_cage/enabled: True
/virtual_cage/north_origin: -500.0
/virtual_cage/east_longitude: 1000.0
/captain/mission_path: '~/catkin_ws/src/cola2_hug/missions'
/captain/tolerance: [1.5, 1.5, 1.0, 0.0, 0.0, 0.1]
/captain/max_distance_to_waypoint: 250.0
/safety_set_zero_velocity/set_zero_velocity_depth: 1.0
/safety_set_zero_velocity/set_zero_velocity_axis: [[False, True, True, True, True, True], [True, True, False, True, True, True], [True, True, True, True, True, False]]
/MORPH/min_reference_commands: 30
/safety/min_imu_update: 10.0
/safety/min_distance_to_wall: 5.0
/safety/max_temperature_bat: 55.0
/safety/usbl_safety_always_on: False
/safety/min_wifi_update: 30.0
/safety/min_nav_update: 2.0
/safety/min_dvl_good_data: 200
/safety/min_modem_update: 400
/safety/min_altitude_update: 60.0
/safety/min_gps_update: 30.0
/safety/max_temperature_pc: 80.0
/safety/min_depth_update: 10.0
/safety/min_dvl_update: 20.0
/safety/min_battery_charge: 0.0
/safe_depth_altitude/min_altitude: 0.8
/safe_depth_altitude/max_depth: 12.0
/safety_set_pose/set_pose_depth: 2.0
/safety_set_pose/set_pose_axis: [[True, True, True, True, False, True], [True, True, True, False, True, True]]
/safety_set_pose/desired_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/diagnostic_aggregator/analyzers/control/path: 'control'
/diagnostic_aggregator/analyzers/control/type: 'GenericAnalyzer'
/diagnostic_aggregator/analyzers/control/name: ['/teleoperation', '/captain', '/hug_actuators', '/controller', 'joystick: Joystick Driver Status']
/diagnostic_aggregator/analyzers/safety/path: 'safety'
/diagnostic_aggregator/analyzers/safety/type: 'GenericAnalyzer'
/diagnostic_aggregator/analyzers/safety/name: ['/safe_depth_altitude', '/virtual_cage', '/up_time', '/diagnostics_supervisor', '/battery', '/check_sensors', '/hug_mon_control_board', '/evologics_modem']
/diagnostic_aggregator/analyzers/navigation/path: 'navigation'
/diagnostic_aggregator/analyzers/navigation/type: 'GenericAnalyzer'
/diagnostic_aggregator/analyzers/navigation/name: ['/navigator', '/fastrax_it_500_gps', '/teledyne_explorer_dvl']
/diagnostic_aggregator/base_path: ''
/diagnostic_aggregator/pub_rate: 1.0
/evologics/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/sim_nav_sensors/water_density: 1000
/sim_nav_sensors/dvl/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/sim_nav_sensors/dvl/velocity_covariance: [0.0015, 0.0015, 0.0015]
/sim_nav_sensors/dvl/period: 0.2
/sim_nav_sensors/imu/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/sim_nav_sensors/imu/orientation_covariance: [0.0001, 0.0001, 0.0001]
/sim_nav_sensors/imu/period: 0.1
/sim_nav_sensors/dvl_type: 'rdi'
/sim_nav_sensors/gps/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/sim_nav_sensors/gps/position_covariance: [0.5, 0.5]
/sim_nav_sensors/gps/period: 1.0
/teleoperation/max_vel: [0.6, 0.0, 0.3, 0.0, 0.0, 0.3]
/teleoperation/actualize_base_pose: True
/teleoperation/base_pose: [0, 0, 0, 0, 0, 0]
/teleoperation/min_pos: [0.0, 0.0, -2.0, -3.14159265359, -1.0, -3.14159265359]
/teleoperation/min_vel: [-0.6, 0.0, -0.3, 0.0, 0.0, -0.3]
/teleoperation/max_pos: [0.0, 0.0, 5.0, 3.14159265359, 1.0, 3.14159265359]
/teleoperation/pose_controlled_axis: [False, False, False, False, False, False]
/controller/max_fin_angle: 40.0
/controller/poly_roll_B: 0.0
/controller/poly_roll_C: 0.0
/controller/poly_roll_A: 0.0
/controller/poly_heave_C: 259.8366
/controller/poly_heave_B: 0.0
/controller/poly_heave_A: 0.0
/controller/d_p_ti: 0.0
/controller/d_p_td: 0.0
/controller/t_yaw_kp: 0.5
/controller/t_heave_fff: 0.26
/controller/max_wrench_Pitch: 17.15
/controller/thruster_distance_yaw: 0.16
/controller/f_pitch_kp: 0.0
/controller/p_sway_fff: 0.0
/controller/t_yaw_fff: 0.0
/controller/t_pitch_ti: 0.0
/controller/t_pitch_td: 0.0
/controller/t_surge_ti: 4.0
/controller/t_surge_td: 0.0
/controller/t_yaw_i_limit: 1.0
/controller/max_force_thruster_forward: 70.0
/controller/t_heave_ti: 7.0
/controller/t_sway_i_limit: 1.0
/controller/poly_surge_percentatge: 0.85
/controller/p_surge_td: 0.0
/controller/p_surge_ti: 0.0
/controller/t_heave_td: 0.5
/controller/t_pitch_i_limit: 1.0
/controller/p_heave_fff: 0.0
/controller/poly_sway_C: 0.0
/controller/poly_sway_B: 0.0
/controller/poly_sway_A: 0.0
/controller/max_velocity_yaw: 0.3
/controller/poly_pitch_A: 0.0
/controller/poly_pitch_B: 0.0
/controller/poly_pitch_C: 0.0
/controller/max_force_thruster_backward: 30.0
/controller/d_p_fff: 0.0
/controller/d_p_i_limit: 0.0
/controller/poly_surge_A: 0.0
/controller/poly_surge_B: 9.9239
/controller/poly_surge_C: 10.1728
/controller/p_pitch_ti: 0.0
/controller/p_pitch_td: 0.0
/controller/t_roll_ti: 0.0
/controller/p_sway_i_limit: 0.0
/controller/p_surge_kp: 0.0
/controller/t_roll_td: 0.0
/controller/max_fin_force: 26.0
/controller/fin_poly: [0.0, 1.0, 0.0, 0.0, 1.0, 0.0]
/controller/TCM: [0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.16783, 0.16783]
/controller/p_yaw_td: 0.6
/controller/p_yaw_ti: 0.0
/controller/d_p_limit: 0.0
/controller/min_fin_angle: -40.0
/controller/t_roll_i_limit: 1.0
/controller/p_sway_kp: 0.0
/controller/p_heave_i_limit: 0.0
/controller/t_heave_i_limit: 1.0
/controller/p_roll_td: 0.0
/controller/p_pitch_i_limit: 0.0
/controller/t_sway_td: 0.5
/controller/p_roll_kp: 0.0
/controller/t_surge_fff: 0.0
/controller/p_roll_ti: 0.0
/controller/f_roll_i_limit: 0.0
/controller/p_heave_ti: 0.0
/controller/t_surge_i_limit: 0.65
/controller/p_heave_td: 0.5
/controller/poly_sway_percentatge: 0.5
/controller/poly_pitch_percentatge: 0.0
/controller/f_pitch_ti: 0.0
/controller/t_pitch_kp: 0.0
/controller/f_pitch_td: 0.0
/controller/p_pitch_fff: 0.0
/controller/t_roll_fff: 0.0
/controller/p_roll_fff: 0.0
/controller/max_wrench_Roll: 3.64
/controller/f_roll_ti: 0.0
/controller/t_sway_ti: 7.0
/controller/poly_yaw_A: 0.0
/controller/poly_yaw_C: 53.2837
/controller/poly_yaw_B: 0.0
/controller/FCM: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.14, 0.14, 0.65, 0.65, 0.0, 0.0]
/controller/f_roll_td: 0.0
/controller/f_roll_fff: 0.0
/controller/t_surge_kp: 0.5
/controller/fin_distance_surge: 0.65
/controller/t_pitch_fff: 0.0
/controller/p_roll_i_limit: 0.0
/controller/p_yaw_kp: 1.5
/controller/max_wrench_Z: 23.3853
/controller/max_wrench_Y: 70.0
/controller/max_wrench_X: 150.0
/controller/t_roll_kp: 0.0
/controller/t_yaw_ti: 5.0
/controller/t_yaw_td: 0.0
/controller/enable_thrusters: True
/controller/max_velocity_pitch: 0.0
/controller/p_sway_td: 0.0
/controller/p_sway_ti: 0.0
/controller/force_to_fins_ratio: 13.0
/controller/poly_roll_percentatge: 0.0
/controller/p_pitch_kp: 0.0
/controller/f_pitch_i_limit: 0.0
/controller/max_velocity_roll: 0.0
/controller/p_surge_fff: 0.0
/controller/d_p_kp: 0.0
/controller/poly_heave_percentatge: 0.7
/controller/p_heave_kp: 0.9
/controller/f_roll_kp: 0.0
/controller/max_velocity_z: 0.3
/controller/max_velocity_y: 0.3
/controller/max_velocity_x: 0.5
/controller/max_wrench_Yaw: 4.7955
/controller/p_surge_i_limit: 0.0
/controller/t_sway_fff: 0.0
/controller/p_yaw_fff: 0.0
/controller/fin_distance_yaw: 0.14
/controller/p_yaw_i_limit: 0.0
/controller/t_heave_kp: 4.0
/controller/t_sway_kp: 4.0
/controller/f_pitch_fff: 0.0
/controller/poly_yaw_percentatge: 0.5
/vehicle_name: 'hug'
/diagnostics_supervisor/timeout: 3600
/pilot/anchor_max_angle_error: 0.5
/pilot/los_cte_min_velocity_ratio: 0.1
/pilot/dubins_yaw_ki: 0.0
/pilot/dubins_lookahead_sec: 4.0
/pilot/anchor_radius: 1.0
/pilot/path_lookahead: 10.0
/pilot/anchor_safety_distance: 50.0
/pilot/los_cte_distance_to_max_velocity: 4.0
/pilot/dubins_yaw_kp: 0.09
/pilot/los_cte_max_surge_velocity: 0.5
/pilot/los_cte_heave_in_3D: False
/pilot/anchor_max_surge: 0.3
/pilot/dubins_acceptance_sec: 3.0
/pilot/anchor_kp: 0.1
/pilot/los_cte_delta: 1.5
/pilot/goto_max_angle_error: 0.3
/pilot/goto_max_surge: 0.5
/pilot/path_surge_speed: 1.0
/pilot/path_tolerance: 2.0
/pilot/anchor_min_surge: -0.1
/pilot/los_cte_min_surge_velocity: 0.2
/pilot/goto_surge_proportional_gain: 0.4
/g500/stereo_front/tf: [0.45, -0.06, -0.12, 80.0, 0.0, 90.0]
/adis_imu/tf: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
/rosversion: '1.12.7
'
/pressure_sensor/tf: [0.389, 0.0, 0.0, 0.0, 0.0, 0.0]
/rosbridge_tcp/fragment_timeout: 600
/rosbridge_tcp/authenticate: False
/rosbridge_tcp/socket_timeout: 10
/rosbridge_tcp/retry_startup_delay: 5
/rosbridge_tcp/host: ''
/rosbridge_tcp/max_message_size: 'None'
/rosbridge_tcp/incoming_buffer: 65536
/rosbridge_tcp/delay_between_messages: 0
/rosbridge_tcp/port: 9091
/recovery_actions/controlled_surface_depth: 0.0
/recovery_actions/frame_id: 'hug'
/recovery_actions/emergency_surface_setpoints: [-0.3, 0.0, 0.0]
/rosdistro: 'kinetic
'
